In [2]:
%pip install chembl_webresource_client

Requirement already satisfied: chembl_webresource_client in /home/susmita/bin/anaconda3/envs/Hypothesis_Testing/lib/python3.11/site-packages (0.10.9)
Requirement already satisfied: urllib3 in /home/susmita/bin/anaconda3/envs/Hypothesis_Testing/lib/python3.11/site-packages (from chembl_webresource_client) (2.7.0)
Requirement already satisfied: requests>=2.18.4 in /home/susmita/bin/anaconda3/envs/Hypothesis_Testing/lib/python3.11/site-packages (from chembl_webresource_client) (2.34.2)
Requirement already satisfied: requests-cache~=1.2 in /home/susmita/bin/anaconda3/envs/Hypothesis_Testing/lib/python3.11/site-packages (from chembl_webresource_client) (1.3.3)
Requirement already satisfied: easydict in /home/susmita/bin/anaconda3/envs/Hypothesis_Testing/lib/python3.11/site-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: attrs>=21.2 in /home/susmita/bin/anaconda3/envs/Hypothesis_Testing/lib/python3.11/site-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Requirement already satisfied: cattrs>=22.2 in /home/susmita/bin/anaconda3/envs/Hypothesis_Testing/lib/python3.11/site-packages (from requests-cache~=1.2->chembl_webresource_client) (26.2.0)
Requirement already satisfied: platformdirs>=2.5 in /home/susmita/bin/anaconda3/envs/Hypothesis_Testing/lib/python3.11/site-packages (from requests-cache~=1.2->chembl_webresource_client) (4.10.0)
Requirement already satisfied: url-normalize>=2.0 in /home/susmita/bin/anaconda3/envs/Hypothesis_Testing/lib/python3.11/site-packages (from requests-cache~=1.2->chembl_webresource_client) (3.0.1)
Requirement already satisfied: typing-extensions>=4.14.0 in /home/susmita/bin/anaconda3/envs/Hypothesis_Testing/lib/python3.11/site-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/susmita/bin/anaconda3/envs/Hypothesis_Testing/lib/python3.11/site-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /home/susmita/bin/anaconda3/envs/Hypothesis_Testing/lib/python3.11/site-packages (from requests>=2.18.4->chembl_webresource_client) (3.18)
Requirement already satisfied: certifi>=2023.5.7 in /home/susmita/bin/anaconda3/envs/Hypothesis_Testing/lib/python3.11/site-packages (from requests>=2.18.4->chembl_webresource_client) (2026.6.17)
Note: you may need to restart the kernel to use updated packages.

In [3]:
from chembl_webresource_client.new_client import new_client

In [4]:
#QSAR dataset, I suggest human acetylcholinesterase (AChE). It is an enzyme
target = new_client.target

target_results = target.search("acetylcholinesterase")

target_results = list(target_results)

len(target_results)

31

In [5]:
target_results[:5]

[{'cross_references': [],
  'organism': 'Drosophila melanogaster',
  'pref_name': 'Acetylcholinesterase',
  'score': 18.0,
  'species_group_flag': False,
  'target_chembl_id': 'CHEMBL2242744',
  'target_components': [{'accession': 'P07140',
    'component_description': 'Acetylcholinesterase',
    'component_id': 7173,
    'component_type': 'PROTEIN',
    'relationship': 'SINGLE PROTEIN',
    'target_component_synonyms': [{'component_synonym': 'Ace',
      'syn_type': 'GENE_SYMBOL'},
     {'component_synonym': 'Acetylcholinesterase', 'syn_type': 'UNIPROT'},
     {'component_synonym': 'Acetylcholinesterase 16 kDa subunit',
      'syn_type': 'UNIPROT'},
     {'component_synonym': 'Acetylcholinesterase 55 kDa subunit',
      'syn_type': 'UNIPROT'},
     {'component_synonym': 'AChE', 'syn_type': 'UNIPROT'},
     {'component_synonym': '3.1.1.7', 'syn_type': 'EC_NUMBER'}],
    'target_component_xrefs': [{'xref_id': '6XYS',
      'xref_name': 'A',
      'xref_src_db': 'PDBe'},
     {'xref_id': '6XYU', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6XYY', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': 'GO:0008233',
      'xref_name': 'peptidase activity',
      'xref_src_db': 'GoFunction'},
     {'xref_id': 'GO:0003990',
      'xref_name': 'acetylcholinesterase activity',
      'xref_src_db': 'GoFunction'},
     {'xref_id': 'GO:0004104',
      'xref_name': 'cholinesterase activity',
      'xref_src_db': 'GoFunction'},
     {'xref_id': 'GO:0017171',
      'xref_name': 'serine hydrolase activity',
      'xref_src_db': 'GoFunction'},
     {'xref_id': 'GO:0042803',
      'xref_name': 'protein homodimerization activity',
      'xref_src_db': 'GoFunction'},
     {'xref_id': 'GO:0043199',
      'xref_name': 'sulfate binding',
      'xref_src_db': 'GoFunction'},
     {'xref_id': 'GO:0052689',
      'xref_name': 'carboxylic ester hydrolase activity',
      'xref_src_db': 'GoFunction'},
     {'xref_id': 'GO:0001507',
      'xref_name': 'acetylcholine catabolic process in synaptic cleft',
      'xref_src_db': 'GoProcess'},
     {'xref_id': 'GO:0006581',
      'xref_name': 'acetylcholine catabolic process',
      'xref_src_db': 'GoProcess'},
     {'xref_id': 'GO:0007268',
      'xref_name': 'chemical synaptic transmission',
      'xref_src_db': 'GoProcess'},
     {'xref_id': 'GO:0019695',
      'xref_name': 'choline metabolic process',
      'xref_src_db': 'GoProcess'},
     {'xref_id': 'GO:0042426',
      'xref_name': 'choline catabolic process',
      'xref_src_db': 'GoProcess'},
     {'xref_id': 'GO:0005615',
      'xref_name': 'extracellular space',
      'xref_src_db': 'GoComponent'},
     {'xref_id': 'GO:0005886',
      'xref_name': 'plasma membrane',
      'xref_src_db': 'GoComponent'},
     {'xref_id': 'GO:0005737',
      'xref_name': 'cytoplasm',
      'xref_src_db': 'GoComponent'},
     {'xref_id': 'GO:0043083',
      'xref_name': 'synaptic cleft',
      'xref_src_db': 'GoComponent'},
     {'xref_id': 'GO:0045202',
      'xref_name': 'synapse',
      'xref_src_db': 'GoComponent'},
     {'xref_id': 'GO:0098552',
      'xref_name': 'side of membrane',
      'xref_src_db': 'GoComponent'},
     {'xref_id': 'Q9VFY0',
      'xref_name': 'Acetylcholinesterase',
      'xref_src_db': 'UniProt'},
     {'xref_id': 'P07140',
      'xref_name': 'Acetylcholinesterase',
      'xref_src_db': 'UniProt'},
     {'xref_id': '6XYS', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6XYU', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6XYY', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': 'P07140', 'xref_name': None, 'xref_src_db': 'AlphaFoldDB'},
     {'xref_id': 'P07140', 'xref_name': None, 'xref_src_db': 'IntAct'},
     {'xref_id': 'R-DME-112311',
      'xref_name': 'Neurotransmitter clearance',
      'xref_src_db': 'Reactome'},
     {'xref_id': 'R-DME-1483191',
      'xref_name': 'Synthesis of PC',
      'xref_src_db': 'Reactome'},
     {'xref_id': 'R-DME-9749641',
      'xref_name': 'Aspirin ADME',
      'xref_src_db': 'Reactome'},
     {'xref_id': 'P07140',
      'xref_name': None,
      'xref_src_db': 'ExpressionAtlas'},
     {'xref_id': 'IPR029058',
      'xref_name': 'AB_hydrolase_fold',
      'xref_src_db': 'InterPro'},
     {'xref_id': 'IPR050654',
      'xref_name': 'AChE-related_enzymes',
      'xref_src_db': 'InterPro'},
     {'xref_id': 'IPR001445',
      'xref_name': 'Acylcholinesterase_insect',
      'xref_src_db': 'InterPro'},
     {'xref_id': 'IPR002018',
      'xref_name': 'CarbesteraseB',
      'xref_src_db': 'InterPro'},
     {'xref_id': 'IPR019826',
      'xref_name': 'Carboxylesterase_B_AS',
      'xref_src_db': 'InterPro'},
     {'xref_id': 'IPR019819',
      'xref_name': 'Carboxylesterase_B_CS',
      'xref_src_db': 'InterPro'},
     {'xref_id': 'IPR000997',
      'xref_name': 'Cholinesterase',
      'xref_src_db': 'InterPro'},
     {'xref_id': 'PTHR43918',
      'xref_name': 'ACETYLCHOLINESTERASE',
      'xref_src_db': 'PANTHER'},
     {'xref_id': 'PTHR43918:SF13',
      'xref_name': 'ACETYLCHOLINESTERASE',
      'xref_src_db': 'PANTHER'},
     {'xref_id': 'PF00135',
      'xref_name': 'COesterase',
      'xref_src_db': 'Pfam'}]}],
  'target_type': 'SINGLE PROTEIN',
  'tax_id': 7227},
 {'cross_references': [],
  'organism': 'Homo sapiens',
  'pref_name': 'Acetylcholinesterase',
  'score': 16.0,
  'species_group_flag': False,
  'target_chembl_id': 'CHEMBL220',
  'target_components': [{'accession': 'P22303',
    'component_description': 'Acetylcholinesterase',
    'component_id': 357,
    'component_type': 'PROTEIN',
    'relationship': 'SINGLE PROTEIN',
    'target_component_synonyms': [{'component_synonym': 'ACHE',
      'syn_type': 'GENE_SYMBOL'},
     {'component_synonym': 'Acetylcholinesterase', 'syn_type': 'UNIPROT'},
     {'component_synonym': 'AChE', 'syn_type': 'UNIPROT'},
     {'component_synonym': '3.1.1.7', 'syn_type': 'EC_NUMBER'}],
    'target_component_xrefs': [{'xref_id': '1F8U',
      'xref_name': 'A',
      'xref_src_db': 'PDBe'},
     {'xref_id': '6U3P', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '4BDT', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6F25', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6U34', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6U37', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '1VZJ', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6O4X', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6O4W', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6WV1', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '4PQE', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6CQU', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6CQT', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6CQW', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6CQV', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6ZWE', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6CQY', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6CQX', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6O50', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6CQZ', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6O52', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '5HFA', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '5HF6', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '5HF5', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '5HF8', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '5HF9', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6O66', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '3LII', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6WVP', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6O5V', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6WVO', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6O69', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6WVQ', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '7E3D', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '9OMT', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '9OMS', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '4EY8', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6NTM', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6NTL', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '5FOQ', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6NTO', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6NTN', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6O5S', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6O5R', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6NTG', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '4EY4', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '4EY5', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6NTH', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '4EY6', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6NTK', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '4EY7', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6WVC', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6WUV', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6WUY', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6WUZ', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '8AEV', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '7P1P', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '2X8B', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '8AEN', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '7RB7', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '5FPQ', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '5HQ3', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '7P1N', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '6NEA', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '8DT2', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '7RB5', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '7RB6', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '8DT7', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '4M0E', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '8DT4', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '4M0F', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '8DT5', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '1B41', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '7D9O', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '7E3H', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '7D9P', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '7XN1', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': '7D9Q', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
     {'xref_id': 'GO:0001540',
      'xref_name': 'amyloid-beta binding',
      'xref_src_db': 'GoFunction'},
     {'xref_id': 'GO:0003990',
      'xref_name': 'acetylcholinesterase activity',
      'xref_src_db': 'GoFunction'},
     {'xref_id': 'GO:0004104',
      'xref_name': 'cholinesterase activity',
      'xref_src_db': 'GoFunction'},
     {'xref_id': 'GO:0005515',
      'xref_name': 'protein binding',
      'xref_src_db': 'GoFunction'},
     {'xref_id': 'GO:0016787',
      'xref_name': 'hydrolase activity',
      'xref_src_db': 'GoFunction'},
     {'xref_id': 'GO:0017171',
      'xref_name': 'serine hydrolase activity',
      'xref_src_db': 'GoFunction'},
     {'xref_id': 'GO:0042166',
      'xref_name': 'acetylcholine binding',
      'xref_src_db': 'GoFunction'},
     {'xref_id': 'GO:0042802',
      'xref_name': 'identical protein binding',
      'xref_src_db': 'GoFunction'},
     {'xref_id': 'GO:0042803',
      'xref_name': 'protein homodimerization activity',
      'xref_src_db': 'GoFunction'},
     {'xref_id': 'GO:0043236',
      'xref_name': 'laminin binding',
      'xref_src_db': 'GoFunction'},
     {'xref_id': 'GO:0052689',
      'xref_name': 'carboxylic ester hydrolase activity',
      'xref_src_db': 'GoFunction'},
     {'xref_id': 'GO:0001507',
      'xref_name': 'acetylcholine catabolic process in synaptic cleft',
      'xref_src_db': 'GoProcess'},
     {'xref_id': 'GO:0001919',
      'xref_name': 'regulation of receptor recycling',
      'xref_src_db': 'GoProcess'},
     {'xref_id': 'GO:0002076',
      'xref_name': 'osteoblast development',
      'xref_src_db': 'GoProcess'},
     {'xref_id': 'GO:0006581',
      'xref_name': 'acetylcholine catabolic process',
      'xref_src_db': 'GoProcess'},
     {'xref_id': 'GO:0007155',
      'xref_name': 'cell adhesion',
      'xref_src_db': 'GoProcess'},
     {'xref_id': 'GO:0007399',
      'xref_name': 'nervous system development',
      'xref_src_db': 'GoProcess'},
     {'xref_id': 'GO:0007416',
      'xref_name': 'synapse assembly',
      'xref_src_db': 'GoProcess'},
     {'xref_id': 'GO:0031623',
      'xref_name': 'receptor internalization',
      'xref_src_db': 'GoProcess'},
     {'xref_id': 'GO:0032223',
      'xref_name': 'negative regulation of synaptic transmission, cholinergic',
      'xref_src_db': 'GoProcess'},
     {'xref_id': 'GO:0050714',
      'xref_name': 'positive regulation of protein secretion',
      'xref_src_db': 'GoProcess'},
     {'xref_id': 'GO:0060041',
      'xref_name': 'retina development in camera-type eye',
      'xref_src_db': 'GoProcess'},
     {'xref_id': 'GO:0095500',
      'xref_name': 'acetylcholine receptor signaling pathway',
      'xref_src_db': 'GoProcess'},
     {'xref_id': 'GO:0120162',
      'xref_name': 'positive regulation of cold-induced thermogenesis',
      'xref_src_db': 'GoProcess'},
     {'xref_id': 'GO:0005576',
      'xref_name': 'extracellular region',
      'xref_src_db': 'GoComponent'},
     {'xref_id': 'GO:0005615',
      'xref_name': 'extracellular space',
      'xref_src_db': 'GoComponent'},
     {'xref_id': 'GO:0005634',
      'xref_name': 'nucleus',
      'xref_src_db': 'GoComponent'},
     {'xref_id': 'GO:0005794',
      'xref_name': 'Golgi apparatus',
      'xref_src_db': 'GoComponent'},
     {'xref_id': 'GO:0005886',
      'xref_name': 'plasma membrane',
      'xref_src_db': 'GoComponent'},
     {'xref_id': 'GO:0009986',
      'xref_name': 'cell surface',
      'xref_src_db': 'GoComponent'},
     {'xref_id': 'GO:0016020',
      'xref_name': 'membrane',
      'xref_src_db': 'GoComponent'},
     {'xref_id': 'GO:0031594',
      'xref_name': 'neuromuscular junction',
      'xref_src_db': 'GoComponent'},
     {'xref_id': 'GO:0043083',
      'xref_name': 'synaptic cleft',
      'xref_src_db': 'GoComponent'},
     {'xref_id': 'GO:0045202',
      'xref_name': 'synapse',
      'xref_src_db': 'GoComponent'},
     {'xref_id': 'GO:0048471',
      'xref_name': 'perinuclear region of cytoplasm',
      'xref_src_db': 'GoComponent'},
     {'xref_id': 'GO:0098552',
      'xref_name': 'side of membrane',
      'xref_src_db': 'GoComponent'},
     {'xref_id': 'PA20',
      'xref_name': 'acetylcholinesterase (Yt blood group)',
      'xref_src_db': 'PharmGKB'},
     {'xref_id': 'A4D2E2',
      'xref_name': 'Acetylcholinesterase',
      'xref_src_db': 'UniProt'},
     {'xref_id': 'B7ZKZ0',
      'xref_name': 'Acetylcholinesterase',
      'xref_src_db': 'UniProt'},
     {'xref_id': 'D6W5X7',
      'xref_name': 'Acetylcholinesterase',
      'xref_src_db': 'UniProt'},
     {'xref_id': 'Q16169',
      'xref_name': 'Acetylcholinesterase',
      'xref_src_db': 'UniProt'},
     {'xref_id': 'Q29S23',
      'xref_name': 'Acetylcholinesterase',
      'xref_src_db': 'UniProt'},
     {'xref_id': 'Q2M324',
      'xref_name': 'Acetylcholinesterase',
      'xref_src_db': 'UniProt'},
     {'xref_id': 'Q504V3',
      'xref_name': 'Acetylcholinesterase',
      'xref_src_db': 'UniProt'},
     {'xref_id': 'Q53F46',
      'xref_name': 'Acetylcholinesterase',
      'xref_src_db': 'UniProt'},
     {'xref_id': 'Q86TM9',
      'xref_name': 'Acetylcholinesterase',
      'xref_src_db': 'UniProt'},
     {'xref_id': 'Q86YX9',
      'xref_name': 'Acetylcholinesterase',
      'xref_src_db': 'UniProt'},
     {'xref_id': 'Q9BXP7',
      'xref_name': 'Acetylcholinesterase',
      'xref_src_db': 'UniProt'},
     {'xref_id': 'P22303',
      'xref_name': 'Acetylcholinesterase',
      'xref_src_db': 'UniProt'},
     {'xref_id': '1B41', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '1F8U', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '1VZJ', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '2X8B', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '3LII', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '4BDT', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '4EY4', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '4EY5', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '4EY6', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '4EY7', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '4EY8', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '4M0E', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '4M0F', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '4PQE', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '5FOQ', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '5FPQ', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '5HF5', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '5HF6', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '5HF8', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '5HF9', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '5HFA', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '5HQ3', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6CQT', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6CQU', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6CQV', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6CQW', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6CQX', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6CQY', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6CQZ', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6F25', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6NEA', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6NTG', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6NTH', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6NTK', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6NTL', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6NTM', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6NTN', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6NTO', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6O4W', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6O4X', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6O50', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6O52', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6O5R', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6O5S', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6O5V', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6O66', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6O69', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6U34', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6U37', 'xref_name': None, 'xref_src_db': 'PDB'},
     {'xref_id': '6U3P', 'xref_name': None, 'xref_src_db': 'PDB'},

In [6]:
target_results[1]

{'cross_references': [],
 'organism': 'Homo sapiens',
 'pref_name': 'Acetylcholinesterase',
 'score': 16.0,
 'species_group_flag': False,
 'target_chembl_id': 'CHEMBL220',
 'target_components': [{'accession': 'P22303',
   'component_description': 'Acetylcholinesterase',
   'component_id': 357,
   'component_type': 'PROTEIN',
   'relationship': 'SINGLE PROTEIN',
   'target_component_synonyms': [{'component_synonym': 'ACHE',
     'syn_type': 'GENE_SYMBOL'},
    {'component_synonym': 'Acetylcholinesterase', 'syn_type': 'UNIPROT'},
    {'component_synonym': 'AChE', 'syn_type': 'UNIPROT'},
    {'component_synonym': '3.1.1.7', 'syn_type': 'EC_NUMBER'}],
   'target_component_xrefs': [{'xref_id': '1F8U',
     'xref_name': 'A',
     'xref_src_db': 'PDBe'},
    {'xref_id': '6U3P', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '4BDT', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6F25', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6U34', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6U37', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '1VZJ', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6O4X', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6O4W', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6WV1', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '4PQE', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6CQU', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6CQT', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6CQW', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6CQV', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6ZWE', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6CQY', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6CQX', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6O50', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6CQZ', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6O52', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '5HFA', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '5HF6', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '5HF5', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '5HF8', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '5HF9', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6O66', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '3LII', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6WVP', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6O5V', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6WVO', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6O69', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6WVQ', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '7E3D', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '9OMT', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '9OMS', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '4EY8', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6NTM', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6NTL', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '5FOQ', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6NTO', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6NTN', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6O5S', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6O5R', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6NTG', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '4EY4', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '4EY5', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6NTH', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '4EY6', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6NTK', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '4EY7', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6WVC', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6WUV', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6WUY', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6WUZ', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '8AEV', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '7P1P', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '2X8B', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '8AEN', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '7RB7', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '5FPQ', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '5HQ3', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '7P1N', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '6NEA', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '8DT2', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '7RB5', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '7RB6', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '8DT7', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '4M0E', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '8DT4', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '4M0F', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '8DT5', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '1B41', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '7D9O', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '7E3H', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '7D9P', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '7XN1', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '7D9Q', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': 'GO:0001540',
     'xref_name': 'amyloid-beta binding',
     'xref_src_db': 'GoFunction'},
    {'xref_id': 'GO:0003990',
     'xref_name': 'acetylcholinesterase activity',
     'xref_src_db': 'GoFunction'},
    {'xref_id': 'GO:0004104',
     'xref_name': 'cholinesterase activity',
     'xref_src_db': 'GoFunction'},
    {'xref_id': 'GO:0005515',
     'xref_name': 'protein binding',
     'xref_src_db': 'GoFunction'},
    {'xref_id': 'GO:0016787',
     'xref_name': 'hydrolase activity',
     'xref_src_db': 'GoFunction'},
    {'xref_id': 'GO:0017171',
     'xref_name': 'serine hydrolase activity',
     'xref_src_db': 'GoFunction'},
    {'xref_id': 'GO:0042166',
     'xref_name': 'acetylcholine binding',
     'xref_src_db': 'GoFunction'},
    {'xref_id': 'GO:0042802',
     'xref_name': 'identical protein binding',
     'xref_src_db': 'GoFunction'},
    {'xref_id': 'GO:0042803',
     'xref_name': 'protein homodimerization activity',
     'xref_src_db': 'GoFunction'},
    {'xref_id': 'GO:0043236',
     'xref_name': 'laminin binding',
     'xref_src_db': 'GoFunction'},
    {'xref_id': 'GO:0052689',
     'xref_name': 'carboxylic ester hydrolase activity',
     'xref_src_db': 'GoFunction'},
    {'xref_id': 'GO:0001507',
     'xref_name': 'acetylcholine catabolic process in synaptic cleft',
     'xref_src_db': 'GoProcess'},
    {'xref_id': 'GO:0001919',
     'xref_name': 'regulation of receptor recycling',
     'xref_src_db': 'GoProcess'},
    {'xref_id': 'GO:0002076',
     'xref_name': 'osteoblast development',
     'xref_src_db': 'GoProcess'},
    {'xref_id': 'GO:0006581',
     'xref_name': 'acetylcholine catabolic process',
     'xref_src_db': 'GoProcess'},
    {'xref_id': 'GO:0007155',
     'xref_name': 'cell adhesion',
     'xref_src_db': 'GoProcess'},
    {'xref_id': 'GO:0007399',
     'xref_name': 'nervous system development',
     'xref_src_db': 'GoProcess'},
    {'xref_id': 'GO:0007416',
     'xref_name': 'synapse assembly',
     'xref_src_db': 'GoProcess'},
    {'xref_id': 'GO:0031623',
     'xref_name': 'receptor internalization',
     'xref_src_db': 'GoProcess'},
    {'xref_id': 'GO:0032223',
     'xref_name': 'negative regulation of synaptic transmission, cholinergic',
     'xref_src_db': 'GoProcess'},
    {'xref_id': 'GO:0050714',
     'xref_name': 'positive regulation of protein secretion',
     'xref_src_db': 'GoProcess'},
    {'xref_id': 'GO:0060041',
     'xref_name': 'retina development in camera-type eye',
     'xref_src_db': 'GoProcess'},
    {'xref_id': 'GO:0095500',
     'xref_name': 'acetylcholine receptor signaling pathway',
     'xref_src_db': 'GoProcess'},
    {'xref_id': 'GO:0120162',
     'xref_name': 'positive regulation of cold-induced thermogenesis',
     'xref_src_db': 'GoProcess'},
    {'xref_id': 'GO:0005576',
     'xref_name': 'extracellular region',
     'xref_src_db': 'GoComponent'},
    {'xref_id': 'GO:0005615',
     'xref_name': 'extracellular space',
     'xref_src_db': 'GoComponent'},
    {'xref_id': 'GO:0005634',
     'xref_name': 'nucleus',
     'xref_src_db': 'GoComponent'},
    {'xref_id': 'GO:0005794',
     'xref_name': 'Golgi apparatus',
     'xref_src_db': 'GoComponent'},
    {'xref_id': 'GO:0005886',
     'xref_name': 'plasma membrane',
     'xref_src_db': 'GoComponent'},
    {'xref_id': 'GO:0009986',
     'xref_name': 'cell surface',
     'xref_src_db': 'GoComponent'},
    {'xref_id': 'GO:0016020',
     'xref_name': 'membrane',
     'xref_src_db': 'GoComponent'},
    {'xref_id': 'GO:0031594',
     'xref_name': 'neuromuscular junction',
     'xref_src_db': 'GoComponent'},
    {'xref_id': 'GO:0043083',
     'xref_name': 'synaptic cleft',
     'xref_src_db': 'GoComponent'},
    {'xref_id': 'GO:0045202',
     'xref_name': 'synapse',
     'xref_src_db': 'GoComponent'},
    {'xref_id': 'GO:0048471',
     'xref_name': 'perinuclear region of cytoplasm',
     'xref_src_db': 'GoComponent'},
    {'xref_id': 'GO:0098552',
     'xref_name': 'side of membrane',
     'xref_src_db': 'GoComponent'},
    {'xref_id': 'PA20',
     'xref_name': 'acetylcholinesterase (Yt blood group)',
     'xref_src_db': 'PharmGKB'},
    {'xref_id': 'A4D2E2',
     'xref_name': 'Acetylcholinesterase',
     'xref_src_db': 'UniProt'},
    {'xref_id': 'B7ZKZ0',
     'xref_name': 'Acetylcholinesterase',
     'xref_src_db': 'UniProt'},
    {'xref_id': 'D6W5X7',
     'xref_name': 'Acetylcholinesterase',
     'xref_src_db': 'UniProt'},
    {'xref_id': 'Q16169',
     'xref_name': 'Acetylcholinesterase',
     'xref_src_db': 'UniProt'},
    {'xref_id': 'Q29S23',
     'xref_name': 'Acetylcholinesterase',
     'xref_src_db': 'UniProt'},
    {'xref_id': 'Q2M324',
     'xref_name': 'Acetylcholinesterase',
     'xref_src_db': 'UniProt'},
    {'xref_id': 'Q504V3',
     'xref_name': 'Acetylcholinesterase',
     'xref_src_db': 'UniProt'},
    {'xref_id': 'Q53F46',
     'xref_name': 'Acetylcholinesterase',
     'xref_src_db': 'UniProt'},
    {'xref_id': 'Q86TM9',
     'xref_name': 'Acetylcholinesterase',
     'xref_src_db': 'UniProt'},
    {'xref_id': 'Q86YX9',
     'xref_name': 'Acetylcholinesterase',
     'xref_src_db': 'UniProt'},
    {'xref_id': 'Q9BXP7',
     'xref_name': 'Acetylcholinesterase',
     'xref_src_db': 'UniProt'},
    {'xref_id': 'P22303',
     'xref_name': 'Acetylcholinesterase',
     'xref_src_db': 'UniProt'},
    {'xref_id': '1B41', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '1F8U', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '1VZJ', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '2X8B', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '3LII', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '4BDT', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '4EY4', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '4EY5', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '4EY6', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '4EY7', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '4EY8', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '4M0E', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '4M0F', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '4PQE', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '5FOQ', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '5FPQ', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '5HF5', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '5HF6', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '5HF8', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '5HF9', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '5HFA', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '5HQ3', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6CQT', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6CQU', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6CQV', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6CQW', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6CQX', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6CQY', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6CQZ', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6F25', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6NEA', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6NTG', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6NTH', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6NTK', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6NTL', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6NTM', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6NTN', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6NTO', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6O4W', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6O4X', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6O50', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6O52', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6O5R', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6O5S', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6O5V', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6O66', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6O69', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6U34', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6U37', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6U3P', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6WUV', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6WUY', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6WUZ', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6WV1', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6WVC', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6WVO', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6WVP', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6WVQ', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '6ZWE', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '7D9O', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '7D9P', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '7D9Q', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '7E3D', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '7E3H', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '7P1N', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '7P1P', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '7RB5', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '7RB6', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '7RB7', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '7XN1', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '8AEN', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '8AEV', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '8DT2', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '8DT4', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '8DT5', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '8DT7', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '9OMS', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '9OMT', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': 'P22303', 'xref_name': None, 'xref_src_db': 'AlphaFoldDB'},
    {'xref_id': 'P22303', 'xref_name': None, 'xref_src_db': 'IntAct'},
    {'xref_id': 'HGNC:108', 'xref_name': 'ACHE', 'xref_src_db': 'HGNC'},
    {'xref_id': 'R-HSA-112311',
     'xref_name': 'Neurotransmitter clearance',
     'xref_src_db': 'Reactome'},
    {'xref_id': 'R-HSA-1483191',
     'xref_name': 'Synthesis of PC',
     'xref_src_db': 'Reactome'},
    {'xref_id': 'R-HSA-422085',
     'xref_name': 'Synthesis, secretion, and deacylation of Ghrelin',
     'xref_src_db': 'Reactome'},
    {'xref_id': 'P22303', 'xref_name': None, 'xref_src_db': 'Pharos'},
    {'xref_id': 'P22303', 'xref_name': None, 'xref_src_db': 'ExpressionAtlas'},
    {'xref_id': 'IPR029058',
     'xref_name': 'AB_hydrolase_fold',
     'xref_src_db': 'InterPro'},
    {'xref_id': 'IPR050654',
     'xref_name': 'AChE-related_enzymes',
     'xref_src_db': 'InterPro'},
    {'xref_id': 'IPR014788',
     'xref_name': 'AChE_tetra',
     'xref_src_db': 'InterPro'},
    {'xref_id': 'IPR002018',
     'xref_name': 'CarbesteraseB',
     'xref_src_db': 'InterPro'},
    {'xref_id': 'IPR019826',
     'xref_name': 'Carboxylesterase_B_AS',
     'xref_src_db': 'InterPro'},
    {'xref_id': 'IPR019819',
     'xref_name': 'Carboxylesterase_B_CS',
     'xref_src_db': 'InterPro'},
    {'xref_id': 'IPR000997',
     'xref_name': 'Cholinesterase',
     'xref_src_db': 'InterPro'},
    {'xref_id': 'PTHR43918',
     'xref_name': 'ACETYLCHOLINESTERASE',
     'xref_src_db': 'PANTHER'},
    {'xref_id': 'PTHR43918:SF11',
     'xref_name': 'ACETYLCHOLINESTERASE',
     'xref_src_db': 'PANTHER'},
    {'xref_id': 'PF08674', 'xref_name': 'AChE_tetra', 'xref_src_db': 'Pfam'},
    {'xref_id': 'PF00135',
     'xref_name': 'COesterase',
     'xref_src_db': 'Pfam'}]}],
 'target_type': 'SINGLE PROTEIN',
 'tax_id': 9606}

In [7]:
human_ache = target_results[1]

print("ChEMBL ID:", human_ache["target_chembl_id"])
print("Name:", human_ache["pref_name"])
print("Organism:", human_ache["organism"])
print("Target type:", human_ache["target_type"])

ChEMBL ID: CHEMBL220
Name: Acetylcholinesterase
Organism: Homo sapiens
Target type: SINGLE PROTEIN

In [10]:
from chembl_webresource_client.new_client import new_client
activity = new_client.activity

ache_ic50 = activity.filter(
    target_chembl_id="CHEMBL220",
    standard_type="IC50"
)
print(activity)
ache_ic50 = list(ache_ic50)

print("Number of IC50 records:", len(ache_ic50))

Number of IC50 records: 10079

In [13]:
ache_ic50[0]

{'action_type': None,
 'activity_comment': None,
 'activity_id': 33969,
 'activity_properties': [],
 'assay_chembl_id': 'CHEMBL643384',
 'assay_description': 'Inhibitory concentration against acetylcholinesterase',
 'assay_type': 'B',
 'assay_variant_accession': None,
 'assay_variant_mutation': None,
 'bao_endpoint': 'BAO_0000190',
 'bao_format': 'BAO_0000357',
 'bao_label': 'single protein format',
 'canonical_smiles': 'CCOc1nn(-c2cccc(OCc3ccccc3)c2)c(=O)o1',
 'data_validity_comment': None,
 'data_validity_description': None,
 'document_chembl_id': 'CHEMBL1148382',
 'document_journal': 'J Med Chem',
 'document_year': 2004,
 'ligand_efficiency': {'bei': '19.61',
  'le': '0.36',
  'lle': '3.32',
  'sei': '9.21'},
 'modality': None,
 'molecule_chembl_id': 'CHEMBL133897',
 'molecule_pref_name': None,
 'parent_molecule_chembl_id': 'CHEMBL133897',
 'pchembl_value': '6.12',
 'potential_duplicate': 0,
 'qudt_units': 'http://www.openphacts.org/units/Nanomolar',
 'record_id': 252547,
 'relation': '=',
 'src_id': 1,
 'standard_flag': 1,
 'standard_relation': '=',
 'standard_text_value': None,
 'standard_type': 'IC50',
 'standard_units': 'nM',
 'standard_upper_value': None,
 'standard_value': '750.0',
 'target_chembl_id': 'CHEMBL220',
 'target_organism': 'Homo sapiens',
 'target_pref_name': 'Acetylcholinesterase',
 'target_tax_id': '9606',
 'text_value': None,
 'toid': None,
 'type': 'IC50',
 'units': 'uM',
 'uo_units': 'UO_0000065',
 'upper_value': None,
 'value': '0.75'}

In [12]:
#Retrieve IC50 activities
ache_ic50[0].keys()

dict_keys(['action_type', 'activity_comment', 'activity_id', 'activity_properties', 'assay_chembl_id', 'assay_description', 'assay_type', 'assay_variant_accession', 'assay_variant_mutation', 'bao_endpoint', 'bao_format', 'bao_label', 'canonical_smiles', 'data_validity_comment', 'data_validity_description', 'document_chembl_id', 'document_journal', 'document_year', 'ligand_efficiency', 'modality', 'molecule_chembl_id', 'molecule_pref_name', 'parent_molecule_chembl_id', 'pchembl_value', 'potential_duplicate', 'qudt_units', 'record_id', 'relation', 'src_id', 'standard_flag', 'standard_relation', 'standard_text_value', 'standard_type', 'standard_units', 'standard_upper_value', 'standard_value', 'target_chembl_id', 'target_organism', 'target_pref_name', 'target_tax_id', 'text_value', 'toid', 'type', 'units', 'uo_units', 'upper_value', 'value'])

In [14]:
record = ache_ic50[0]

fields = [
    "molecule_chembl_id",
    "canonical_smiles",
    "standard_type",
    "standard_relation",
    "standard_value",
    "standard_units",
    "pchembl_value",
    "assay_chembl_id",
    "assay_type",
    "target_chembl_id"
]

for field in fields:
    print(f"{field:22s}: {record[field]}")

molecule_chembl_id    : CHEMBL133897
canonical_smiles      : CCOc1nn(-c2cccc(OCc3ccccc3)c2)c(=O)o1
standard_type         : IC50
standard_relation     : =
standard_value        : 750.0
standard_units        : nM
pchembl_value         : 6.12
assay_chembl_id       : CHEMBL643384
assay_type            : B
target_chembl_id      : CHEMBL220

In [16]:
import pandas as pd

columns = [
    "molecule_chembl_id",
    "canonical_smiles",
    "standard_type",
    "standard_relation",
    "standard_value",
    "standard_units",
    "pchembl_value",
    "assay_chembl_id",
    "assay_type",
    "target_chembl_id"
]

df = pd.DataFrame(ache_ic50)[columns]

df.head()

,molecule_chembl_id,canonical_smiles,standard_type,standard_relation,standard_value,standard_units,pchembl_value,assay_chembl_id,assay_type,target_chembl_id
0,CHEMBL133897,CCOc1nn(-c2cccc(OCc3ccccc3)c2)c(=O)o1,IC50,=,750.0,nM,6.12,CHEMBL643384,B,CHEMBL220
1,CHEMBL336398,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC1CC1,IC50,=,100.0,nM,7.00,CHEMBL643384,B,CHEMBL220
2,CHEMBL131588,CN(C(=O)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F)c1ccccc1,IC50,>,50000.0,nM,NaN,CHEMBL643384,B,CHEMBL220
3,CHEMBL130628,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F,IC50,=,300.0,nM,6.52,CHEMBL643384,B,CHEMBL220
4,CHEMBL130478,CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)C,IC50,=,800.0,nM,6.10,CHEMBL643384,B,CHEMBL220

In [17]:
df.shape

(10079, 10)

In [18]:
df["standard_type"].value_counts(dropna=False)

standard_type
IC50    10079
Name: count, dtype: int64

In [19]:
df["standard_relation"].value_counts(dropna=False)

standard_relation
=      7901
NaN    1286
>       875
<        13
~         2
>>        2
Name: count, dtype: int64

In [20]:
df["standard_units"].value_counts(dropna=False)

standard_units
nM             8723
NaN            1265
ug.mL-1          83
10'5pM            3
10'6pM            2
10^-4microM       2
10'3pM            1
Name: count, dtype: int64

In [21]:
df[
    [
        "canonical_smiles",
        "standard_value",
        "standard_units",
        "pchembl_value"
    ]
].isna().sum()

canonical_smiles      39
standard_value      1286
standard_units      1265
pchembl_value       2804
dtype: int64

In [22]:
df_exact = df[df["standard_relation"] == "="].copy()

print("Raw records:", len(df))
print("Exact IC50 records:", len(df_exact))

Raw records: 10079
Exact IC50 records: 7901

In [23]:
df_clean = df_exact[
    df_exact["standard_units"] == "nM"
].copy()

print("Exact records:", len(df_exact))
print("Exact + nM records:", len(df_clean))

Exact records: 7901
Exact + nM records: 7827

In [24]:
df_clean[
    [
        "canonical_smiles",
        "standard_value",
        "pchembl_value"
    ]
].isna().sum()

canonical_smiles      1
standard_value        0
pchembl_value       552
dtype: int64

In [25]:
df_clean = df_clean.dropna(
    subset=["canonical_smiles", "standard_value"]
).copy()

In [26]:
df_clean["standard_value"] = pd.to_numeric(
    df_clean["standard_value"],
    errors="coerce"
)

df_clean = df_clean.dropna(subset=["standard_value"])

In [29]:
import numpy as np

df_clean["pIC50"] = -np.log10(df_clean["standard_value"] * 1e-9)

In [30]:
df_clean[
    ["standard_value", "standard_units", "pIC50", "pchembl_value"]
].head(10)

    standard_value standard_units     pIC50 pchembl_value
0            750.0             nM  6.124939          6.12
1            100.0             nM  7.000000          7.00
3            300.0             nM  6.522879          6.52
4            800.0             nM  6.096910          6.10
5           2400.0             nM  5.619789          5.62
6            100.0             nM  7.000000          7.00
8            800.0             nM  6.096910          6.10
11            50.0             nM  7.301030          7.30
13           560.0             nM  6.251812          6.25
16          1400.0             nM  5.853872          5.85

In [31]:
comparison = df_clean.dropna(subset=["pchembl_value"]).copy()

comparison["pchembl_value"] = pd.to_numeric(
    comparison["pchembl_value"]
)

comparison["difference"] = (
    comparison["pIC50"] - comparison["pchembl_value"]
)

comparison[
    ["standard_value", "pIC50", "pchembl_value", "difference"]
].head(10)

    standard_value     pIC50  pchembl_value  difference
0            750.0  6.124939           6.12    0.004939
1            100.0  7.000000           7.00    0.000000
3            300.0  6.522879           6.52    0.002879
4            800.0  6.096910           6.10   -0.003090
5           2400.0  5.619789           5.62   -0.000211
6            100.0  7.000000           7.00    0.000000
8            800.0  6.096910           6.10   -0.003090
11            50.0  7.301030           7.30    0.001030
13           560.0  6.251812           6.25    0.001812
16          1400.0  5.853872           5.85    0.003872

In [32]:
comparison["difference"].describe()

count    7274.000000
mean       -0.000213
std         0.002789
min        -0.005496
25%        -0.002427
50%        -0.000012
75%         0.001952
max         0.005489
Name: difference, dtype: float64

In [33]:
print("Number of activity records:", len(df_clean))
print(
    "Number of unique molecules:",
    df_clean["molecule_chembl_id"].nunique()
)

Number of activity records: 7826
Number of unique molecules: 6288

In [34]:
measurement_counts = (
    df_clean["molecule_chembl_id"]
    .value_counts()
)

measurement_counts.head(10)

molecule_chembl_id
CHEMBL95        185
CHEMBL502       165
CHEMBL659        86
CHEMBL636        58
CHEMBL94         53
CHEMBL395280     23
CHEMBL292314     19
CHEMBL433041     13
CHEMBL140476     13
CHEMBL345124     13
Name: count, dtype: int64

In [35]:
most_measured = measurement_counts.index[0]

print("Molecule:", most_measured)

df_clean[
    df_clean["molecule_chembl_id"] == most_measured
][
    [
        "molecule_chembl_id",
        "standard_value",
        "standard_units",
        "pIC50",
        "assay_chembl_id",
        "assay_type"
    ]
].sort_values("pIC50")

Molecule: CHEMBL95

,molecule_chembl_id,standard_value,standard_units,pIC50,assay_chembl_id,assay_type
8830,CHEMBL95,1180.00,nM,5.928118,CHEMBL5217010,B
1742,CHEMBL95,1030.00,nM,5.987163,CHEMBL900444,B
1791,CHEMBL95,926.00,nM,6.033389,CHEMBL900177,B
2672,CHEMBL95,800.00,nM,6.096910,CHEMBL1249049,B
6372,CHEMBL95,600.00,nM,6.221849,CHEMBL4047916,B
...,...,...,...,...,...,...
6264,CHEMBL95,19.95,nM,7.700057,CHEMBL4023561,B
6259,CHEMBL95,18.50,nM,7.732828,CHEMBL4023561,B
7224,CHEMBL95,12.59,nM,7.899974,CHEMBL4356264,B
5771,CHEMBL95,7.53,nM,8.123205,CHEMBL3789779,B
3032,CHEMBL95,3.16,nM,8.500313,CHEMBL1816232,B

In [36]:
repeat_stats = (
    df_clean
    .groupby("molecule_chembl_id")["pIC50"]
    .agg(["count", "mean", "median", "std", "min", "max"])
)

repeat_stats["range"] = (
    repeat_stats["max"] - repeat_stats["min"]
)

repeat_stats.sort_values(
    "range",
    ascending=False
).head(10)

,count,mean,median,std,min,max,range
molecule_chembl_id,,,,,,,
CHEMBL225198,4,7.797106,7.721849,3.082318,5.045757,10.698970,5.653213
CHEMBL194823,8,8.286299,9.596879,2.431521,4.346787,9.602060,5.255273
CHEMBL382260,2,11.744058,11.744058,3.616104,9.187087,14.301030,5.113943
CHEMBL199670,2,11.801030,11.801030,3.535534,9.301030,14.301030,5.000000
CHEMBL225567,4,8.062953,7.926936,2.738714,5.698970,10.698970,5.000000
CHEMBL502,165,7.616130,7.744727,0.680938,3.703335,8.698970,4.995635
CHEMBL370807,2,11.823909,11.823909,3.503178,9.346787,14.301030,4.954243
CHEMBL225326,3,7.894677,9.221849,2.667501,4.823909,9.638272,4.814363
CHEMBL1203984,2,5.232125,5.232125,3.397488,2.829738,7.634512,4.804774
CHEMBL223443,3,8.258230,9.698970,2.689849,5.154902,9.920819,4.765917

In [37]:
df_final = (
    df_clean
    .groupby("molecule_chembl_id")
    .agg(
        canonical_smiles=("canonical_smiles", "first"),
        pIC50=("pIC50", "median"),
        n_measurements=("pIC50", "count")
    )
    .reset_index()
)

df_final.head()

,molecule_chembl_id,canonical_smiles,pIC50,n_measurements
0,CHEMBL100334,CN(CCOCCNC(=S)NC(=O)c1ccccc1)Cc1ccccc1,6.920819,1
1,CHEMBL100366,CN1CC[C@@]2(C)c3cc(OC(=O)Nc4ccccc4)ccc3N(C=O)C12,6.107683,1
2,CHEMBL100510,CN(CCOCCNC(=S)NC(=O)c1ccc2ccccc2c1)Cc1ccccc1,7.000000,1
3,CHEMBL101028,CN(CCOCCNC(=S)Nc1ccc(OC(F)(F)F)cc1)Cc1ccccc1,6.000000,1
4,CHEMBL101155,CN(CCOCCCNC(=S)NC(=O)c1ccccc1)Cc1ccccc1,5.958607,1

In [38]:
print("Final number of molecules:", len(df_final))

Final number of molecules: 6288

In [39]:
from rdkit import Chem

df_final["mol"] = df_final["canonical_smiles"].apply(
    Chem.MolFromSmiles
)

invalid = df_final["mol"].isna().sum()

print("Invalid SMILES:", invalid)

Invalid SMILES: 0

In [40]:
df_final[df_final["mol"].isna()][
    ["molecule_chembl_id", "canonical_smiles"]
]

Empty DataFrame
Columns: [molecule_chembl_id, canonical_smiles]
Index: []

In [45]:
#df_final = df_final[df_final["mol"].notna()].copy()

In [46]:
#df_final = df_final.drop(columns=["mol"])

In [47]:
df_final.head()

,molecule_chembl_id,canonical_smiles,pIC50,n_measurements
0,CHEMBL100334,CN(CCOCCNC(=S)NC(=O)c1ccccc1)Cc1ccccc1,6.920819,1
1,CHEMBL100366,CN1CC[C@@]2(C)c3cc(OC(=O)Nc4ccccc4)ccc3N(C=O)C12,6.107683,1
2,CHEMBL100510,CN(CCOCCNC(=S)NC(=O)c1ccc2ccccc2c1)Cc1ccccc1,7.000000,1
3,CHEMBL101028,CN(CCOCCNC(=S)Nc1ccc(OC(F)(F)F)cc1)Cc1ccccc1,6.000000,1
4,CHEMBL101155,CN(CCOCCCNC(=S)NC(=O)c1ccccc1)Cc1ccccc1,5.958607,1

In [48]:
print("Final dataset size:", df_final.shape)

Final dataset size: (6288, 4)

In [54]:
df_final.to_csv(
    "ache_ic50_clean.csv",
    index=False
)

In [53]:
print("Saved:", df_final.shape)

Saved: (6288, 4)

In [51]:
df_check = pd.read_csv("ache_ic50_clean.csv")

print(df_check.shape)
df_check.head()

(6288, 4)

,molecule_chembl_id,canonical_smiles,pIC50,n_measurements
0,CHEMBL100334,CN(CCOCCNC(=S)NC(=O)c1ccccc1)Cc1ccccc1,6.920819,1
1,CHEMBL100366,CN1CC[C@@]2(C)c3cc(OC(=O)Nc4ccccc4)ccc3N(C=O)C12,6.107683,1
2,CHEMBL100510,CN(CCOCCNC(=S)NC(=O)c1ccc2ccccc2c1)Cc1ccccc1,7.000000,1
3,CHEMBL101028,CN(CCOCCNC(=S)Nc1ccc(OC(F)(F)F)cc1)Cc1ccccc1,6.000000,1
4,CHEMBL101155,CN(CCOCCCNC(=S)NC(=O)c1ccccc1)Cc1ccccc1,5.958607,1

In [55]:
df_final.to_csv(
    "data/ache_ic50_clean.csv",
    index=False
)

NameError: name 'comparison' is not defined